# Datasource H2
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc=true
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:test

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Console H2
quarkus.h2.console.enabled=true
quarkus.h2.console.path=localhost:8080//h2-console

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
